### ISSUE TITLE
Using "magic-scrolll" for body scrollbar

### ISSUE THREAD

**Issue by Serjilio** [mudin/magic-scroll#1]
I try to make it work for main scroll of the body. So I pass "body" string to the document query selector. But it do not work. Scrolling isn't smooth. Is there any way to make it work? Or any ideas to make smooth scroll on user action (wheel, keyboard, touchpad)?

Thanks!

Here is an example of my object init:

let magicScroll = new MagicScroll({
    target: document.querySelector("body"),
    speed: 160,
    smooth: 24
});

**Comment by mudin** [comment]
@Serjilio Actually it needs extra effort to make it work. You should do some css I guess

**Comment by mudin** [comment]
@Serjilio please check the returning value in `onUpdate`

**Comment by mudin** [comment]
@Serjilio Can you try with new version 1.0.8? for body you don't need to set target. default is body. 
And I also added umd bundle. 
Here is the demo: https://jsfiddle.net/mudin/2nstb5pf/

**Comment by Serjilio** [comment]
> @Serjilio Can you try with new version 1.0.8? for body you don't need to set target. default is body.
> And I also added umd bundle.
> Here is the demo: https://jsfiddle.net/mudin/2nstb5pf/

Thank you for the feedback!

Yeah, it does work, but scroll isn't smooth in your example anyway. Yes, it is different from native srcoll. But in the first momentum we have a little shake.

Check the video, please: https://www.loom.com/share/a690701e42ba47d7b81ea6b6dd3e4324

**Comment by mudin** [comment]
@Serjilio Can you try to change the parameters?
